
FROM jenkins/jenkins


MAINTAINER Andrew_Mironenko <a.mironenko66@gmail.com>


#COPY dk1.sh /
#COPY sc1.sh /
#COPY runapp.sh /
#COPY doing.sh /

#RUN /sc1.sh

#EXPOSE 5000


#ENTRYPOINT ["/runapp.sh","start"]



